# Generated by Django 4.2.5 on 2023-10-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'curso'},
        ),
    ]
